apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8scert-secret-permission  
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - get
  - watch
  - list
  - create
  - delete
  - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8scerts-service-account
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8scert-create-secret-rbac
  
subjects:
- kind: ServiceAccount
  name: k8scerts-service-account
  
roleRef:
  kind: Role
  name: k8scert-secret-permission
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k8scert-creation-job  
spec:
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      serviceAccountName: k8scerts-service-account
      containers:
      - name: k8scert-creation
        image: "gcr.io/mesh7-public-images/tools:latest"
        command:
        - "/bin/bash"
        - "-c"
        - |
          set -e
          openssl rand -out /root/.rnd -hex 256
          openssl genrsa -out /tmp/ca.key 2048
          openssl req -x509 -new -nodes -key /tmp/ca.key -subj "/CN=apiserver" -days 10000 -out /tmp/ca.crt
          kubectl create secret generic customapi-ca --from-file=/tmp/ca.key --from-file=/tmp/ca.crt -n $KUBERNETES_POD_NAMESPACE --dry-run -o yaml | kubectl apply -f -
        env:
          - name: KUBERNETES_POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-apiserver
  labels:
    app: kube-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-apiserver
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
      labels:
        app: kube-apiserver
    spec:
      initContainers:
      - name: check-etcd-server
        image: "gcr.io/mesh7-public-images/tools:latest"
        command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              URL="http://etcd:2379"
              curl -k --retry 30 --retry-delay 20 --connect-timeout 30 --max-time 30 $URL
              if [[ $? -ne 0 ]];then
                echo "$URL not reachable....."
                exit 1
              fi
      containers:
      - command:
        - kube-apiserver
        - --insecure-bind-address=0.0.0.0
        - --etcd-servers=http://etcd:2379
        - --service-account-key-file=/custom/k8s/certs/ca.crt
        - --service-cluster-ip-range=10.24.0.0/16
        - --cert-dir=/etc/kubernetes/certs
        - --endpoint-reconciler-type=none
        - --port=8080
        image: gcr.io/nsx-sm/k8s.gcr.io/kube-apiserver:v1.18.0
        ports:
          - containerPort: 8080
        env:
        - name: KUBERNETES_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        name: kube-apiserver
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15    
        volumeMounts:
            - name: customapi-ca
              mountPath: "/custom/k8s/certs"
              readOnly: true
      restartPolicy: Always
      securityContext: {}
      volumes:
      - name: customapi-ca
        secret:
            secretName: customapi-ca
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
  
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 6443
      name: https
      targetPort: 6443
  selector:
      app: kube-apiserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-controllermanager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-controllermanager
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
      labels:
        name: kube-controllermanager
    spec:
      initContainers:
      - name: check-etcd-server
        image: "gcr.io/mesh7-public-images/tools:latest"
        command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              URL="http://etcd:2379"
              curl -k --retry 30 --retry-delay 20 --connect-timeout 30 --max-time 30 $URL
              if [[ $? -ne 0 ]];then
                echo "$URL not reachable....."
                exit 1
              fi
      containers:
      - command:
        - kube-controller-manager
        - --service-account-private-key-file=/custom/k8s/certs/ca.key
        - --leader-elect=false
        - --master=apiserver:8080
        - --use-service-account-credentials=true
        - --authentication-skip-lookup=true
        image: gcr.io/nsx-sm/k8s.gcr.io/kube-controller-manager:v1.18.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /healthz
            port: 10257
            scheme: HTTPS
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: kube-controllermanager
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
            - name: customapi-ca
              mountPath: "/custom/k8s/certs"
              readOnly: true
      restartPolicy: Always
      securityContext: {}
      volumes:
      - name: customapi-ca
        secret:
            secretName: customapi-ca
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-container 
  labels:
    app: proxy-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-container
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
      labels:
        app: proxy-container
    spec:
      containers:
      - name: proxy-container
        image: "gcr.io/nsx-sm/m7/debug-container:latest"
        command: [ "kubectl","--server=http://apiserver:8080","proxy","--address=0.0.0.0","--disable-filter=true","--v=1" ]
        ports:
          - containerPort: 8001
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 200Mi
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-container
spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8001
  selector:
      app: proxy-container
