image:
  name: runner.servicemesh.biz:5000/allspark/runner:latest

variables:
  REPOSITORY: nsx-allspark_users/nexus-sdk/cli

before_script:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
  - git config --global url."https://gitlab.eng.vmware.com/".insteadOf "git@gitlab.eng.vmware.com:"
  - git config --global gc.auto 0
  - git config --global credential.helper store

.setup_aws: &setup_aws
  - apt clean && apt update -y && apt install unzip -y
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip" -o "awscliv2.zip"
  - unzip -qq awscliv2.zip
  - ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  -  docker login --username AWS -p $(aws ecr get-login-password --region us-west-2) 284299419820.dkr.ecr.us-west-2.amazonaws.com

build:
  stage: build
  script:
    - *setup_aws
    - make build
    