image:
  name: harbor-repo.vmware.com/nexus/runner:latest

include:
- project: "nsx-allspark_users/nexus-sdk/integration-tests"
  ref: master
  file: ".gitlab-ci-template.yml"


before_script:
  - git config --global url."https://gitlab.eng.vmware.com/".insteadOf "git@gitlab.eng.vmware.com:"
  - git config --global gc.auto 0
  - git config --global credential.helper store
  - export GOPRIVATE=*.eng.vmware.com
  - export GOINSECURE=*.eng.vmware.com
  - echo -e  "https://gitlab-ci-token:${CICD_TOKEN}@gitlab.eng.vmware.com/" >> ~/.git-credentials
  - docker login harbor-repo.vmware.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - export CONTAINER_ID=$(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=$CI_JOB_ID" -f "label=com.gitlab.gitlab-runner.type=build")
  - export PKG_NAME=/builds/nsx-allspark_users/nexus-sdk/authz-controller
  - docker login --username AWS -p $(aws ecr get-login-password --region us-west-2) 284299419820.dkr.ecr.us-west-2.amazonaws.com



build:
  stage: build
  only:
    - master
    - merge_requests
  script:
    - make docker IMAGE_TAG=$CI_COMMIT_SHA
    - make publish IMAGE_TAG=$CI_COMMIT_SHA
    - make publish IMAGE_REGISTRY="284299419820.dkr.ecr.us-west-2.amazonaws.com/nexus/authz" IMAGE_TAG=$CI_COMMIT_SHA


build_tag:
  stage: build
  only:
    - tags
  script:
    - make docker IMAGE_TAG=$CI_COMMIT_TAG
    - make publish IMAGE_TAG=$CI_COMMIT_TAG
    - make publish IMAGE_REGISTRY="284299419820.dkr.ecr.us-west-2.amazonaws.com/nexus/authz" IMAGE_TAG=$CI_COMMIT_TAG

coverage:
  before_script:
    - git config --global url."https://gitlab.eng.vmware.com/".insteadOf "git@gitlab.eng.vmware.com:"
    - git config --global gc.auto 0
    - git config --global credential.helper store
    - export GOPRIVATE=*.eng.vmware.com
    - echo -e  "https://gitlab-ci-token:${CICD_TOKEN}@gitlab.eng.vmware.com/" >> ~/.git-credentials
  image: runner.servicemesh.biz:5000/allspark/runner:latest
  stage: test
  variables:
    GIT_DEPTH: 0
  only:
    - merge_requests
    - master
  script:
    - make coverage
    - sonar-scanner

unit-test:
  stage: test
  only:
    - merge_requests
    - master
  script:
    - make unit-test

integration_test:
  stage: integration_test
  variables:
    NEXUS_AUTHZ_CONTROLLER_TEMPLATE_VERSION: $CI_COMMIT_SHA
  only:
    - merge_requests
    - master
  extends: .run_integration_test


stages:
  - build
  - test
  - integration_test
