image:
  name: harbor-repo.vmware.com/nexus/runner:latest

include:
- project: "nsx-allspark_users/nexus-sdk/integration-tests"
  file: ".gitlab-ci-template.yml"

variables:
  REPOSITORY: nsx-allspark_users/nexus-sdk/cli

before_script:
  - git config --global url."https://gitlab.eng.vmware.com/".insteadOf "git@gitlab.eng.vmware.com:"
  - git config --global gc.auto 0
  - git config --global credential.helper store
  - echo -e  "https://gitlab-ci-token:${CICD_TOKEN}@gitlab.eng.vmware.com/" >> ~/.git-credentials
  - echo $GCLOUD_SERVICE_KEY > key.json
  - gcloud auth activate-service-account --key-file key.json
  - echo $GCLOUD_AUTH_SERVICE_KEY | docker login -u _json_key --password-stdin gcr.io

build:
  stage: build
  only:
    - merge_requests
    - master
  variables:
    TAG: $CI_COMMIT_SHA
  script:
    - make docker_publish
    - flash docker scan image gcr.io/nsx-sm/nexus/nexus-api:$CI_COMMIT_SHA

build_tag:
  stage: build
  only:
    - tags
  variables:
    TAG: $CI_COMMIT_TAG
    VERSION: $CI_COMMIT_TAG
  script:
    - make docker_publish
    - flash docker scan image gcr.io/nsx-sm/nexus/nexus-api:$CI_COMMIT_TAG


integration_test:
  stage: integration_test
  variables:
    NEXUS_API_DATAMODEL_CRD_VERSION: $CI_COMMIT_SHA
  only:
    - merge_requests
    - master
  extends: .run_integration_test

stages:
  - build
  - integration_test
