image:
  name: runner.servicemesh.biz:5000/allspark/runner:latest

before_script:
  - git config --global url."https://gitlab.eng.vmware.com/".insteadOf "git@gitlab.eng.vmware.com:"
  - git config --global gc.auto 0
  - git config --global credential.helper store
  - export GOPRIVATE=*.eng.vmware.com
  - echo -e  "https://gitlab-ci-token:${CICD_TOKEN}@gitlab.eng.vmware.com/" >> ~/.git-credentials
  - echo $GCLOUD_AUTH_SERVICE_KEY | docker login -u _json_key --password-stdin gcr.io
  - export CONTAINER_ID=$(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=$CI_JOB_ID" -f "label=com.gitlab.gitlab-runner.type=build")


build:
  stage: build
  only:
    - master
    - merge_requests
  script:
    - make docker.builder
    - CONTAINER_ID=$CONTAINER_ID PKG_NAME=$(realpath .) make publish IMAGE_TAG=$CI_COMMIT_SHA

build_tag:
  stage: build
  only:
    - tags
  script:
    - make docker.builder
    - CONTAINER_ID=$CONTAINER_ID PKG_NAME=$(realpath .) make publish IMAGE_TAG=$CI_COMMIT_TAG
    
stages:
  - build