image:
  name: harbor-repo.vmware.com/nexus/runner:latest

include:
- project: "nsx-allspark_users/nexus-sdk/integration-tests"
  file: ".gitlab-ci-template.yml"

before_script:
  - git config --global url."https://gitlab.eng.vmware.com/".insteadOf "git@gitlab.eng.vmware.com:"
  - git config --global gc.auto 0
  - git config --global credential.helper store
  - echo -e  "https://gitlab-ci-token:${CICD_TOKEN}@gitlab.eng.vmware.com/" >> ~/.git-credentials
  - echo $GCLOUD_SERVICE_KEY > key.json
  - gcloud auth activate-service-account --key-file key.json

.git_config: &git_config
  - git config --global user.name gitlab-tsm
  - git config --global user.email gitlab-tsm@vmware.com

.setup_aws: &setup_aws
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - docker login --username AWS -p $(aws ecr get-login-password --region us-west-2) 284299419820.dkr.ecr.us-west-2.amazonaws.com

.create_builder: &create_builder
  - export CONTAINER_ID=$(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=$CI_JOB_ID" -f "label=com.gitlab.gitlab-runner.type=build")
  - make docker.builder

.harbor_login: &harbor_login
  - docker login harbor-repo.vmware.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

build:
  stage: build
  only:
    - merge_requests
    - master
  script:
   - *setup_aws
   - *create_builder
   - *harbor_login
   - CONTAINER_ID=$CONTAINER_ID PKG_NAME=$(realpath .) make build_in_container
   - PKG_NAME=$(realpath .) make docker
   - make publish
   - make publish.ecr
   - make publish_template

test:
  stage: test
  only:
    - merge_requests
    - master
  script:
   - *setup_aws
   - *create_builder
   - CONTAINER_ID=$CONTAINER_ID PKG_NAME=$(realpath .)  make test_in_container


build_tag:
  stage: build
  only:
    - tags
  script:
   - *setup_aws
   - *create_builder
   - *harbor_login
   - CONTAINER_ID=$CONTAINER_ID PKG_NAME=$(realpath .) make build_in_container
   - PKG_NAME=$(realpath .) make docker TAG=$CI_COMMIT_TAG
   - make publish TAG=$CI_COMMIT_TAG
   - make publish.ecr TAG=$CI_COMMIT_TAG
   - make publish_template TAG=$CI_COMMIT_TAG


coverage:
  stage: test
  variables:
    GIT_DEPTH: 0
  before_script:
    - git config --global url."https://gitlab.eng.vmware.com/".insteadOf "git@gitlab.eng.vmware.com:"
    - git config --global gc.auto 0
    - git config --global credential.helper store
    - export GOPRIVATE=*.eng.vmware.com
    - echo -e  "https://gitlab-ci-token:${CICD_TOKEN}@gitlab.eng.vmware.com/" >> ~/.git-credentials
  image: runner.servicemesh.biz:5000/allspark/runner:latest
  only:
    - merge_requests
    - master
  script:
    - make coverage
    - sonar-scanner

integration_test:
  stage: integration_test
  variables:
    NEXUS_VALIDATION_TEMPLATE_VERSION: $CI_COMMIT_SHA
  only:
    - merge_requests
    - master
  extends: .run_integration_test


stages:
  - build
  - test
  - integration_test
