nexusCli:
  version: v0.0.32
nexusCompiler:
  version: v0.0.8
nexusAppTemplates:
  version: v0.0.4
nexusDatamodelTemplates:
  version: v0.0.10
nexusValidation:
  version: v0.0.5
nexusApiGateway:
  version: v0.0.2
