nexusCli:
  version: v0.0.118
nexusCompiler:
  version: v0.0.49
nexusAppTemplates:
  version: v0.0.10
nexusDatamodelTemplates:
  version: v0.0.22
nexusRuntime:
  version: v0.2.37
tsmCli:
  version: v0.0.3
