nexusCli:
  version: v0.0.104
nexusCompiler:
  version: v0.0.40
nexusAppTemplates:
  version: v0.0.9
nexusDatamodelTemplates:
  version: v0.0.20
nexusRuntime:
  version: v0.2.32
tsmCli:
  version: v0.0.2
