nexusCli:
  version: v0.0.120
nexusCompiler:
  version: v0.0.51
nexusAppTemplates:
  version: v0.0.10
nexusDatamodelTemplates:
  version: v0.0.22
nexusRuntime:
  version: v0.2.38
tsmCli:
  version: v0.0.3
