nexusCli:
  version: v0.0.139
nexusCompiler:
  version: v0.0.58
nexusAppTemplates:
  version: v0.0.10
nexusDatamodelTemplates:
  version: v0.0.22
nexusRuntime:
  version: v0.2.53
tsmCli:
  version: v0.0.3
