nexusCli:
  version: v0.0.68
nexusCompiler:
  version: v0.0.25
nexusAppTemplates:
  version: v0.0.9
nexusDatamodelTemplates:
  version: v0.0.16
nexusValidation:
  version: v0.0.8
nexusApiGateway:
  version: v0.0.17
nexusApiDatamodelCrds:
  version: v0.0.8
nexusRuntime:
  version: v0.1.4
nexusConnectController:
  version: v0.0.1
