nexusCli:
  version: v0.0.153
nexusCompiler:
  version: v0.0.60
nexusAppTemplates:
  version: v0.0.10
nexusDatamodelTemplates:
  version: v0.0.22
nexusRuntime:
  version: v0.2.61
tsmCli:
  version: v0.0.4
