nexusCli:
  version: v0.0.135
nexusCompiler:
  version: v0.0.58
nexusAppTemplates:
  version: v0.0.10
nexusDatamodelTemplates:
  version: v0.0.22
nexusRuntime:
  version: v0.2.51
tsmCli:
  version: v0.0.3
