nexusCli:
  version: v0.0.40
nexusCompiler:
  version: v0.0.13
nexusAppTemplates:
  version: v0.0.7
nexusDatamodelTemplates:
  version: v0.0.10
nexusValidation:
  version: v0.0.5
nexusApiGateway:
  version: v0.0.5
nexusApiDatamodelCrds:
  version: v0.0.2
