nexusCli:
  version: v0.0.46
nexusCompiler:
  version: v0.0.14
nexusAppTemplates:
  version: v0.0.7
nexusDatamodelTemplates:
  version: v0.0.13
nexusValidation:
  version: v0.0.7
nexusApiGateway:
  version: v0.0.8
nexusApiOperator:
  version: v0.0.4
nexusApiDatamodelCrds:
  version: v0.0.4
nexusRuntime:
  version: v0.1.0
