nexusCli:
  version: v0.0.37
nexusCompiler:
  version: v0.0.12
nexusAppTemplates:
  version: v0.0.7
nexusDatamodelTemplates:
  version: v0.0.10
nexusValidation:
  version: v0.0.5
nexusApiGateway:
  version: v0.0.5
