nexusCli:
  version: v0.0.111
nexusCompiler:
  version: v0.0.42
nexusAppTemplates:
  version: v0.0.10
nexusDatamodelTemplates:
  version: v0.0.22
nexusRuntime:
  version: v0.2.34
tsmCli:
  version: v0.0.3
