nexusCli:
  version: v0.0.131
nexusCompiler:
  version: v0.0.58
nexusAppTemplates:
  version: v0.0.10
nexusDatamodelTemplates:
  version: v0.0.22
nexusRuntime:
  version: v0.2.47
tsmCli:
  version: v0.0.3
