nexusCli:
  version: v0.0.160
nexusCompiler:
  version: v0.0.62
nexusAppTemplates:
  version: v0.0.10
nexusDatamodelTemplates:
  version: v0.0.22
nexusRuntime:
  version: v0.2.63
tsmCli:
  version: v0.0.4
