apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "nexus-validation.webhook.svc"
webhooks:
  - name: "nexus-validation-crd.webhook.svc"
    rules:
      - apiGroups: [ "root.tsm.tanzu.vmware.com", "config.tsm.tanzu.vmware.com" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE" ]
        resources: [ "*" ]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: nexus-validation
        path: /validate
        port: 443
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lVTXZKY3J0N0Vt
        TS83VHF6VTVTNXhDQ2lJb21Bd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tERUxNQWtHQTFVRUJoTUNR
        VlV4R1RBWEJnTlZCQU1NRUc1bGVIVnpMWFpoYkdsa1lYUnBiMjR3SGhjTgpNakl3TXpNd01UTXhN
        REl6V2hjTk1qTXdNek13TVRNeE1ESXpXakFvTVFzd0NRWURWUVFHRXdKQlZURVpNQmNHCkExVUVB
        d3dRYm1WNGRYTXRkbUZzYVdSaGRHbHZiakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFE
        Q0MKQVFvQ2dnRUJBS1pUOEdZZWpPK3d5QlFmZ0VuUTNLOHdUTDlzYjJhUWoyazFnUUJucEFoVHZ3
        WEpXNEc3S0R1VAo2YmIzTEFDd0JVeG1OZXdNMkRFZmRJOG15VHphaU5lUzZtWWV2S2gzU3B3cGpy
        Qks1VHVxZXFjY2FsL3RNOWdwCmhHdjZSOFdheUNyUDZBZ2dtdDNxdDkyVC9pNTJtMW50d2JUU21D
        NUNCZHA4dWlOb21nMVB3RnFla1JocEVrKy8Ka0VQVkE4endJbUlIZVo3UERoTGpWSndVRENCRlRG
        cGNwU1lRSUpuYUNrWEw3am9FQ3haYTFwUGpRaVZnc2JDRApOTFQvZ284RzE2WDZ4SU1lZCsySmk3
        a08xOG91NHpzakhpSmtiSmQ3eFEzbkYrQ05JVWpSTTVEVExCVXJ6TEQ0CnM2eXo2ZFlVWTBEZHhD
        Y0hPRzlvYnBjWFhGYWpOdVVDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkpxY3dHaUEKUVFHL1Mr
        MHcramVRaFlzMi9HQ01NQjhHQTFVZEl3UVlNQmFBRkpxY3dHaUFRUUcvUyswdytqZVFoWXMyL0dD
        TQpNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSDF6Y3hu
        blpBT1ROdVR4Ck9pVFI0bytrWGRKQjBXN0tRVnR6V3ViRkdEVStnQnRuR1ZRcElQM0hkV2Y0MTNo
        U3BBeG9saVVBRHF5M1RXSjQKcjEvWXJ3bEdSSkc2MVBWR29yd0lBTnZuakt0VTYwZnRTdDhtWk44
        eDRvMUFyZlVvMGNLSk5jNVlEdXp4aGhLcApLdmFvaDFkcFJ2T2F2MWVzMERwbmUyQXRTNytQR2Vo
        ZHhiV1gzZmtDNlFvSkN6QkpmZjJnNDBNcm92Yjcwa2kzCmN1U1l2UUx3R1BtcTEzSkZuSy9oVW5F
        UGZqTjlJTnY2TkpTUWJCeW1FSmYydE1XMjNDaVh3d01tZXNqT05MQUgKRGc5UWM2QXpZWEw2NjdP
        NmpVYXFuTUZmQmJRbk1OL0tpWlFrOTE3YTM0SUVmdFBXQWcxbWJWNkhseTd5YldSawppbW4xeWFN
        PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: [ "v1", "v1beta1" ]
    sideEffects: None
  - name: "nexus-validation-crd-type.webhook.svc"
    rules:
      - apiGroups: [ "apiextensions.k8s.io" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE", "UPDATE" ]
        resources: [ "customresourcedefinitions" ]
        scope: "Cluster"
    clientConfig:
      service:
        namespace: default
        name: nexus-validation
        path: /validate-crd-type
        port: 443
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lVTXZKY3J0N0Vt
        TS83VHF6VTVTNXhDQ2lJb21Bd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tERUxNQWtHQTFVRUJoTUNR
        VlV4R1RBWEJnTlZCQU1NRUc1bGVIVnpMWFpoYkdsa1lYUnBiMjR3SGhjTgpNakl3TXpNd01UTXhN
        REl6V2hjTk1qTXdNek13TVRNeE1ESXpXakFvTVFzd0NRWURWUVFHRXdKQlZURVpNQmNHCkExVUVB
        d3dRYm1WNGRYTXRkbUZzYVdSaGRHbHZiakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFE
        Q0MKQVFvQ2dnRUJBS1pUOEdZZWpPK3d5QlFmZ0VuUTNLOHdUTDlzYjJhUWoyazFnUUJucEFoVHZ3
        WEpXNEc3S0R1VAo2YmIzTEFDd0JVeG1OZXdNMkRFZmRJOG15VHphaU5lUzZtWWV2S2gzU3B3cGpy
        Qks1VHVxZXFjY2FsL3RNOWdwCmhHdjZSOFdheUNyUDZBZ2dtdDNxdDkyVC9pNTJtMW50d2JUU21D
        NUNCZHA4dWlOb21nMVB3RnFla1JocEVrKy8Ka0VQVkE4endJbUlIZVo3UERoTGpWSndVRENCRlRG
        cGNwU1lRSUpuYUNrWEw3am9FQ3haYTFwUGpRaVZnc2JDRApOTFQvZ284RzE2WDZ4SU1lZCsySmk3
        a08xOG91NHpzakhpSmtiSmQ3eFEzbkYrQ05JVWpSTTVEVExCVXJ6TEQ0CnM2eXo2ZFlVWTBEZHhD
        Y0hPRzlvYnBjWFhGYWpOdVVDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkpxY3dHaUEKUVFHL1Mr
        MHcramVRaFlzMi9HQ01NQjhHQTFVZEl3UVlNQmFBRkpxY3dHaUFRUUcvUyswdytqZVFoWXMyL0dD
        TQpNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSDF6Y3hu
        blpBT1ROdVR4Ck9pVFI0bytrWGRKQjBXN0tRVnR6V3ViRkdEVStnQnRuR1ZRcElQM0hkV2Y0MTNo
        U3BBeG9saVVBRHF5M1RXSjQKcjEvWXJ3bEdSSkc2MVBWR29yd0lBTnZuakt0VTYwZnRTdDhtWk44
        eDRvMUFyZlVvMGNLSk5jNVlEdXp4aGhLcApLdmFvaDFkcFJ2T2F2MWVzMERwbmUyQXRTNytQR2Vo
        ZHhiV1gzZmtDNlFvSkN6QkpmZjJnNDBNcm92Yjcwa2kzCmN1U1l2UUx3R1BtcTEzSkZuSy9oVW5F
        UGZqTjlJTnY2TkpTUWJCeW1FSmYydE1XMjNDaVh3d01tZXNqT05MQUgKRGc5UWM2QXpZWEw2NjdP
        NmpVYXFuTUZmQmJRbk1OL0tpWlFrOTE3YTM0SUVmdFBXQWcxbWJWNkhseTd5YldSawppbW4xeWFN
        PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: [ "v1", "v1beta1" ]
    sideEffects: None
