---
apiVersion: v1
kind: Service
metadata:
  name: nexus-validation
spec:
  type: NodePort
  selector:
    app: nexus-validation
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
      nodePort: 30443
