apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-calibrate
  labels:
    app: nexus-calibrate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-calibrate
  template:
    metadata:
      labels:
        app: nexus-calibrate
    spec:
      containers:
      - name: nexus-calibrate
        image: 284299419820.dkr.ecr.us-west-2.amazonaws.com/nexus/nexus-calib:tv0.0.27
        command: ["/bin/calib"]
        volumeMounts:
        - name: config
          mountPath: "/root/config/"
          readOnly: true
        - name: rest-calls
          mountPath: "/root/rest-calls/"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: nexus-calib-config
            items:
            - key: "conf.yaml"
              path: "conf.yaml"
        - name: rest-calls
          configMap:
            name: rest-calls
            items:
            - key: "rest_data.yaml"
              path: "rest_data.yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-calibrate
spec:
  selector:
    app: nexus-calibrate
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
