apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-dmb-kubeconfig-api-gw
  namespace: {{.Values.global.namespace}}
data:
  config: |
    current-context: api-gw
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        api-version: v1
        server: http://nexus-api-gw:80
        insecure-skip-tls-verify: true
      name: api-gw
    contexts:
    - context:
        cluster: api-gw
      name: api-gw
---
apiVersion: batch/v1
kind: Job
metadata:
  name: nexus-api-dm-obj-installer
  namespace: {{.Values.global.namespace}}
spec:
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      activeDeadlineSeconds: 300
      containers:
        - name: nexus-api-dm-obj-creator
          image: "gcr.io/nsx-sm/tools:latest"
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-c"
            - |
              set -e
              function create_object() {
                FILE=$1
                RETRY=4
                ATTEMPT=0
                while [ $ATTEMPT -ne $RETRY ]; do
                if ! cat $FILE | kubectl apply -f -; then
                   ATTEMPT=$((ATTEMPT + 1))
                   if [ $ATTEMPT -ne $RETRY ]; then
                      sleep 2
                   else
                      exit 1
                   fi
                else
                   break
                fi
                done
              }
              echo 'waiting for nexus-apiserver to be ready'
              until $(curl --output /dev/null --silent --head --fail http://nexus-apiserver:8080/readyz); do
                echo '.'
                sleep 5
              done

              if ! kubectl get crds datamodels.nexus.org > /dev/null 2>&1 ; then
              echo 'creating Datamodel CRD type'
                cat > /tmp/object <<EOF
                  apiVersion: apiextensions.k8s.io/v1
                  kind: CustomResourceDefinition
                  metadata:
                    creationTimestamp: null
                    name: datamodels.nexus.org
                  spec:
                    conversion:
                      strategy: None
                    group: nexus.org
                    names:
                      kind: Datamodel
                      listKind: DatamodelList
                      plural: datamodels
                      shortNames:
                      - datamodel
                      singular: datamodel
                    scope: Cluster
                    versions:
                    - name: v1
                      schema:
                        openAPIV3Schema:
                          type: object
                          properties:
                            apiVersion:
                              type: string
                            kind:
                              type: string
                            metadata:
                              type: object
                            spec:
                              properties:
                                name:
                                  type: string
                                url:
                                  type: string
                                title:
                                  type: string
                                  default: "Nexus API GW APIs"
                              type: object
                      served: true
                      storage: true
              EOF
                kubectl -s nexus-apiserver:8080 apply -f /tmp/object
              fi
              echo 'waiting for api-gw to be ready'
              until $(curl --output /dev/null --silent --head --fail http://nexus-api-gw/readyz); do
                echo '.'
                sleep 5
              done
              echo 'api-gw is now ready'

              echo 'waiting for Nexus CRD to be installed...'
              until $(kubectl get crd/nexuses.api.nexus.org > /dev/null 2>&1); do
                echo '.'
                sleep 5
              done
              echo 'Nexus CRD is installed'

              if ! kubectl get nexuses.api.nexus.org -l nexus/display_name=default -o=jsonpath='{.items[0]}' > /dev/null 2>&1 ; then
                echo 'creating Nexus node'
                cat > /tmp/object <<EOF
                apiVersion: api.nexus.org/v1
                kind: Nexus
                metadata:
                  name: default
              EOF
                create_object /tmp/object
              fi

              echo 'waiting for Config CRD to be installed...'
              until $(kubectl get crd/configs.config.nexus.org > /dev/null 2>&1); do
                echo '.'
                sleep 5
              done
              echo 'Config CRD is installed'

              if ! kubectl get configs.config.nexus.org -l nexus/display_name=default -o=jsonpath='{.items[0]}' > /dev/null 2>&1 ; then
                echo 'creating Config node'
                cat > /tmp/object <<EOF
                apiVersion: config.nexus.org/v1
                kind: Config
                metadata:
                  name: default
                  labels:
                    nexuses.api.nexus.org: default
              EOF
              create_object /tmp/object
              fi

              echo 'waiting for Connect CRD to be installed...'
              until $(kubectl get crd/connects.connect.nexus.org > /dev/null 2>&1); do
                echo '.'
                sleep 5
              done
              echo 'Connect CRD is installed'

              if ! kubectl get connects.connect.nexus.org -l nexus/display_name=default -o=jsonpath='{.items[0]}' > /dev/null 2>&1 ; then
                echo 'creating Connect node'
                cat > /tmp/object <<EOF
                apiVersion: connect.nexus.org/v1
                kind: Connect
                metadata:
                  name: default
                  labels:
                    nexuses.api.nexus.org: default
                    configs.config.nexus.org: default
              EOF
              create_object /tmp/object
              fi

              echo 'waiting for ApiGateway CRD to be installed...'
              until $(kubectl get crd/apigateways.apigateway.nexus.org > /dev/null 2>&1); do
                echo '.'
                sleep 5
              done
              echo 'ApiGateway CRD is installed'

              if ! kubectl get apigateways.apigateway.nexus.org -l nexus/display_name=default -o=jsonpath='{.items[0]}' > /dev/null 2>&1 ; then
                echo 'creating ApiGateway node'
                cat > /tmp/object <<EOF
                apiVersion: apigateway.nexus.org/v1
                kind: ApiGateway
                metadata:
                  name: default
                  labels:
                    nexuses.api.nexus.org: default
                    configs.config.nexus.org: default
              EOF
              create_object /tmp/object
              fi


          env:
            - name: KUBECONFIG
              value: /kube/config
          volumeMounts:
            - mountPath: /kube
              name: kubeconfig
      volumes:
        - name: kubeconfig
          configMap:
            name: nexus-dmb-kubeconfig-api-gw
      restartPolicy: OnFailure
  backoffLimit: 10
