resources:
- deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: api-gw
  newName: 284299419820.dkr.ecr.us-west-2.amazonaws.com/nexus/api-gw
  newTag: api-gw-1ab556ba
